# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Saber < Formula
  desc "Run Saber signal research from your terminal"
  homepage "https://saber.app"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/saberapp/cli/releases/download/v0.1.5/saber_0.1.5_darwin_amd64.tar.gz"
      sha256 "3db73e19d27e2621fdaf4a3037a03eb08a9e481b6e51bc64709d7073a502806d"

      define_method(:install) do
        bin.install "saber"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/saberapp/cli/releases/download/v0.1.5/saber_0.1.5_darwin_arm64.tar.gz"
      sha256 "ff94d30a02ba21f277d1753dbe60eefd925a972b99f9a09011541235ef8265cb"

      define_method(:install) do
        bin.install "saber"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/saberapp/cli/releases/download/v0.1.5/saber_0.1.5_linux_amd64.tar.gz"
      sha256 "c0095c26960634225a577404df77209008a15b33a1aeee52822a8b2d7ae9d25a"
      define_method(:install) do
        bin.install "saber"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/saberapp/cli/releases/download/v0.1.5/saber_0.1.5_linux_arm64.tar.gz"
      sha256 "92054a3736865e9ee2b9257f5aec0db2f40f9183929e5d36218123b775572eb2"
      define_method(:install) do
        bin.install "saber"
      end
    end
  end

  test do
    system "#{bin}/saber", "version"
  end
end
