# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Saber < Formula
  desc "Run Saber signal research from your terminal"
  homepage "https://saber.app"
  version "0.1.13"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/saberapp/cli/releases/download/v0.1.13/saber_0.1.13_darwin_amd64.tar.gz"
      sha256 "41dd5e2e207ff57f782276334729553375c61d1cf060b64bde72f083f7e3036d"

      define_method(:install) do
        bin.install "saber"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/saberapp/cli/releases/download/v0.1.13/saber_0.1.13_darwin_arm64.tar.gz"
      sha256 "f542c329074d34528399d759169b616863296975cbf7cdb01054029a1c8ab37e"

      define_method(:install) do
        bin.install "saber"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/saberapp/cli/releases/download/v0.1.13/saber_0.1.13_linux_amd64.tar.gz"
      sha256 "2e985b764f656b7d027b0cb67b1f54368e908ba288ca2ddde3de013d7c4ae8e8"
      define_method(:install) do
        bin.install "saber"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/saberapp/cli/releases/download/v0.1.13/saber_0.1.13_linux_arm64.tar.gz"
      sha256 "6318d20c50c3ab4de31011b5a22b606caa041ffc3faeb585fbf664427046df21"
      define_method(:install) do
        bin.install "saber"
      end
    end
  end

  test do
    system "#{bin}/saber", "version"
  end
end
